[project]
name = 'tipz-stacks-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
# Using Clarity 4 with Clarinet 3.11.0
[contracts.sip-010-trait]
path = 'contracts/traits/sip-010-trait.clar'
clarity_version = 4
epoch = 'latest'

[contracts.cheer-token]
path = 'contracts/cheer-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.tipz-core]
path = 'contracts/tipz-core.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
